### ISSUE TITLE
Meeting Action Items: 2018-09-13

### ISSUE THREAD

**Issue by keywordnew** [nodejs/website-redesign#118]
Thanks for attending folks! Y'all are the best 🎉💯🎉

# Action Items for [2018-12-06](https://github.com/nodejs/website-redesign/blob/master/meetings/2018-12-06.md) meeting
 - [ ] @chowdhurian: to deploy site for [issue 428 in CommComm repo](https://github.com/nodejs/community-committee/issues/428). The site will be a jump off point for the eventual Community (Committee) site.
 - [ ] @bnb: to design card for [issue 428 in CommComm repo](https://github.com/nodejs/community-committee/issues/428) to carry the link to our contributor landing page
 - [ ] @lidoravitan: to review the effectiveness of the card and landing page in [issue 428 in CommComm repo](https://github.com/nodejs/community-committee/issues/428)

**Comment by amiller-gh** [comment]
🙏
