### ISSUE TITLE
Meeting Action Items: 2018-09-13 

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/website-redesign#90]
> Going to experiment with different ways to track action items from meetings over the next few weeks. Here's attempt number one – in a dedicated issue. We'll review action items from the previous meeting in the next one.

# Action Items for [2018-09-13](https://github.com/nodejs/website-redesign/blob/master/meetings/2018-09-13.md) meeting
 - [ ] @tolmasky: to provide screenshots or live demo for visual review on PR #22831.
 - [x] @chowdhurian: Set up demo of feedback system (User Voice?), comment in issue #60.
 - [x] @bnb: Start draft of "Node.js Monitoring" conceptual information doc, link with PR #84 (can track this in separate ticket).
 - [x] @chowdhurian: Follow up with author of PR #83.
 - [x] @amiller-gh: Make ticket for Meetup docs hackathons discussion. (edit: see #99)
 - [x] @bnb: Link to supplemental content for #85 for author reference and iteration.
 - [x] @chowdhurian: Drive engagement on #13, request PR from eojthebrave if they have specific feedback

**Comment by amiller-gh** [comment]
All but one completed, will follow up individually on that final item! Good job team 🎉
